train_data_path: "data/training"
val_data_path: "data/validation"
output_path: "outputs"
model_path: "checkpoints"
load_chkpt: null # continue training
name: "test"

# Training parameters
epochs: 100

# Optimizer configurations
optimizer: "AdamW"
lr: 0.0001
scheduler: "CustomCosineAnnealingWarmupRestarts"
scheduler_interval: "epoch"  # or "step"
scheduler_param:
  first_cycle_steps: 20  # epoch
  cycle_mult: 2
  max_lr: 0.0002
  min_lr: 0.000025
  warmup_steps: 1
  gamma: 0.5

# Parameters for model architectures
craft:
  PAD : False  # maybe good for generalization
  image_size : 1536
  THRESHOLD_POSITIVE : 0.1
  THRESHOLD_NEGATIVE : 0.0
  THRESHOLD_FSCORE: 0.5
  THRESHOLD_WORD : 0.7
  THRESHOLD_CHARACTER: 0.7
  THRESHOLD_AFFINITY: 0.3